name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  RUST_BACKTRACE: 1

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    name: Foundry project
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest

      - name: Show Forge version
        run: |
          forge --version
          cast --version
          anvil --version

      - name: Install dependencies
        run: |
          forge install OpenZeppelin/openzeppelin-contracts --no-commit
          forge install foundry-rs/forge-std --no-commit

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Run Forge coverage
        run: |
          forge coverage --report lcov
        id: coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
